service: apollo-lambda

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  graphql:
    handler: index.graphqlHandler
    events:
      - http:
          path: /productFunction
          method: post
      - http:
          path: /productFunction
          method: get
